name: multi-region

on:
  push:
    branches:
      - support-multi-region

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - name: Test Login
        uses: lenheri/login-action@test
        with:
          registry: 344732144681.dkr.ecr.us-east-1.amazonaws.com/bazz
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
