name: multi-region

on:
  push:
    branches:
      - support-multi-region

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - name: Test Login
        uses: lenheri/login-action@support-multi-region
        with:
          ecr: true
          # registry: 344732144681.dkr.ecr.us-west-1.amazonaws.com/bazz
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGIONS: 'us-east-1,us-west-1'
          AWS_ACCOUNT_IDS: 344732144681
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Manual build and push
        run: |
          docker buildx build \
          -t 344732144681.dkr.ecr.us-east-1.amazonaws.com/bazz:foo \
          -t 344732144681.dkr.ecr.us-west-1.amazonaws.com/bazz:foo \
          .
          --push
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            344732144681.dkr.ecr.us-east-1.amazonaws.com/bazz:foo
            344732144681.dkr.ecr.us-west-1.amazonaws.com/bazz:foo
